// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package algorithms

// ComparatorByte is a function that given two elements of type byte returns x such that:
// x < 0 iff e1 < e2
// x > 0 iff e1 > e2
// x = 0 iff e1 = e2
type ComparatorByte func(e1, e2 byte) int

func MergeSortByte(array []byte, compare ComparatorByte) {
	b := append([]byte(nil), array...) // shallow copy
	mergeSortByte(array, compare, 0, len(array)-1, b)
}

func mergeSortByte(array []byte, compare ComparatorByte, low, high int, b []byte) {
	if low >= high {
		return
	}

	middle := low + (high-low)/2
	mergeSortByte(array, compare, low, middle, b)
	mergeSortByte(array, compare, middle+1, high, b)
	mergeByte(array, compare, low, middle, high, b)
}

func mergeByte(array []byte, compare ComparatorByte, low int, middle int, high int, b []byte) {

	for i := low; i <= middle; i++ {
		b[i] = array[i]
	}
	for i := middle + 1; i <= high; i++ {
		b[i] = array[i]
	}

	lowQueue := low
	highQueue := middle + 1
	i := low
	for ; lowQueue <= middle && highQueue <= high; i++ {
		if compare(b[lowQueue], b[highQueue]) > 0 { // b[lowQueue] > b[highQueue]
			array[i] = b[highQueue]
			highQueue++
		} else {
			array[i] = b[lowQueue]
			lowQueue++
		}
	}

	for ; lowQueue <= middle; i++ {
		array[i] = b[lowQueue]
		lowQueue++
	}

	for ; highQueue <= high; i++ {
		array[i] = b[highQueue]
		highQueue++
	}
}
