// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package algorithms

// ComparatorString is a function that given two elements of type string returns x such that:
// x < 0 iff e1 < e2
// x > 0 iff e1 > e2
// x = 0 iff e1 = e2
type ComparatorString func(e1, e2 string) int

func MergeSortString(array []string, compare ComparatorString) {
	b := append([]string(nil), array...) // shallow copy
	mergeSortString(array, compare, 0, len(array)-1, b)
}

func mergeSortString(array []string, compare ComparatorString, low, high int, b []string) {
	if low >= high {
		return
	}

	middle := low + (high-low)/2
	mergeSortString(array, compare, low, middle, b)
	mergeSortString(array, compare, middle+1, high, b)
	mergeString(array, compare, low, middle, high, b)
}

func mergeString(array []string, compare ComparatorString, low int, middle int, high int, b []string) {

	for i := low; i <= middle; i++ {
		b[i] = array[i]
	}
	for i := middle + 1; i <= high; i++ {
		b[i] = array[i]
	}

	lowQueue := low
	highQueue := middle + 1
	i := low
	for ; lowQueue <= middle && highQueue <= high; i++ {
		if compare(b[lowQueue], b[highQueue]) > 0 { // b[lowQueue] > b[highQueue]
			array[i] = b[highQueue]
			highQueue++
		} else {
			array[i] = b[lowQueue]
			lowQueue++
		}
	}

	for ; lowQueue <= middle; i++ {
		array[i] = b[lowQueue]
		lowQueue++
	}

	for ; highQueue <= high; i++ {
		array[i] = b[highQueue]
		highQueue++
	}
}
