// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package algorithms

// ComparatorFloat32 is a function that given two elements of type float32 returns x such that:
// x < 0 iff e1 < e2
// x > 0 iff e1 > e2
// x = 0 iff e1 = e2
type ComparatorFloat32 func(e1, e2 float32) int

func MergeSortFloat32(array []float32, compare ComparatorFloat32) {
	b := append([]float32(nil), array...) // shallow copy
	mergeSortFloat32(array, compare, 0, len(array)-1, b)
}

func mergeSortFloat32(array []float32, compare ComparatorFloat32, low, high int, b []float32) {
	if low >= high {
		return
	}

	middle := low + (high-low)/2
	mergeSortFloat32(array, compare, low, middle, b)
	mergeSortFloat32(array, compare, middle+1, high, b)
	mergeFloat32(array, compare, low, middle, high, b)
}

func mergeFloat32(array []float32, compare ComparatorFloat32, low int, middle int, high int, b []float32) {

	for i := low; i <= middle; i++ {
		b[i] = array[i]
	}
	for i := middle + 1; i <= high; i++ {
		b[i] = array[i]
	}

	lowQueue := low
	highQueue := middle + 1
	i := low
	for ; lowQueue <= middle && highQueue <= high; i++ {
		if compare(b[lowQueue], b[highQueue]) > 0 { // b[lowQueue] > b[highQueue]
			array[i] = b[highQueue]
			highQueue++
		} else {
			array[i] = b[lowQueue]
			lowQueue++
		}
	}

	for ; lowQueue <= middle; i++ {
		array[i] = b[lowQueue]
		lowQueue++
	}

	for ; highQueue <= high; i++ {
		array[i] = b[highQueue]
		highQueue++
	}
}
