// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package algorithms

// ComparatorInt64 is a function that given two elements of type int64 returns x such that:
// x < 0 iff e1 < e2
// x > 0 iff e1 > e2
// x = 0 iff e1 = e2
type ComparatorInt64 func(e1, e2 int64) int

func MergeSortInt64(array []int64, compare ComparatorInt64) {
	b := append([]int64(nil), array...) // shallow copy
	mergeSortInt64(array, compare, 0, len(array)-1, b)
}

func mergeSortInt64(array []int64, compare ComparatorInt64, low, high int, b []int64) {
	if low >= high {
		return
	}

	middle := low + (high-low)/2
	mergeSortInt64(array, compare, low, middle, b)
	mergeSortInt64(array, compare, middle+1, high, b)
	mergeInt64(array, compare, low, middle, high, b)
}

func mergeInt64(array []int64, compare ComparatorInt64, low int, middle int, high int, b []int64) {

	for i := low; i <= middle; i++ {
		b[i] = array[i]
	}
	for i := middle + 1; i <= high; i++ {
		b[i] = array[i]
	}

	lowQueue := low
	highQueue := middle + 1
	i := low
	for ; lowQueue <= middle && highQueue <= high; i++ {
		if compare(b[lowQueue], b[highQueue]) > 0 { // b[lowQueue] > b[highQueue]
			array[i] = b[highQueue]
			highQueue++
		} else {
			array[i] = b[lowQueue]
			lowQueue++
		}
	}

	for ; lowQueue <= middle; i++ {
		array[i] = b[lowQueue]
		lowQueue++
	}

	for ; highQueue <= high; i++ {
		array[i] = b[highQueue]
		highQueue++
	}
}
