// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package algorithms

// ComparatorInterface is a function that given two elements of type interface{} returns x such that:
// x < 0 iff e1 < e2
// x > 0 iff e1 > e2
// x = 0 iff e1 = e2
type ComparatorInterface func(e1, e2 interface{}) int

func MergeSortInterface(array []interface{}, compare ComparatorInterface) {
	b := append([]interface{}(nil), array...) // shallow copy
	mergeSortInterface(array, compare, 0, len(array)-1, b)
}

func mergeSortInterface(array []interface{}, compare ComparatorInterface, low, high int, b []interface{}) {
	if low >= high {
		return
	}

	middle := low + (high-low)/2
	mergeSortInterface(array, compare, low, middle, b)
	mergeSortInterface(array, compare, middle+1, high, b)
	mergeInterface(array, compare, low, middle, high, b)
}

func mergeInterface(array []interface{}, compare ComparatorInterface, low int, middle int, high int, b []interface{}) {

	for i := low; i <= middle; i++ {
		b[i] = array[i]
	}
	for i := middle + 1; i <= high; i++ {
		b[i] = array[i]
	}

	lowQueue := low
	highQueue := middle + 1
	i := low
	for ; lowQueue <= middle && highQueue <= high; i++ {
		if compare(b[lowQueue], b[highQueue]) > 0 { // b[lowQueue] > b[highQueue]
			array[i] = b[highQueue]
			highQueue++
		} else {
			array[i] = b[lowQueue]
			lowQueue++
		}
	}

	for ; lowQueue <= middle; i++ {
		array[i] = b[lowQueue]
		lowQueue++
	}

	for ; highQueue <= high; i++ {
		array[i] = b[highQueue]
		highQueue++
	}
}
